/**
 * Mock Data for DevForge V2 - FASE 5
 * Dados de exemplo para testar todos os componentes
 */

import type {
  Feature,
  Sprint,
  Phase,
  HumanMember,
  AIAgent,
  Activity,
  Question,
} from '../types';

// Sprint Data
export const MOCK_SPRINT: Sprint = {
  number: 3,
  goal: 'Sistema de reservas completo + painel admin',
  daysLeft: 3,
  totalDays: 7,
  velocity: {
    avg: 28,
    history: [22, 31, 28],
  },
};

export const MOCK_FEATURES: Feature[] = [
  {
    id: 'f1',
    title: 'Sistema de notificações push',
    type: 'FEATURE',
    priority: 'LOW',
    pts: 5,
    status: 'BACKLOG',
    desc: 'Notificações em tempo real',
  },
  {
    id: 'f2',
    title: 'Exportar reservas para CSV',
    type: 'FEATURE',
    priority: 'MEDIUM',
    pts: 3,
    status: 'BACKLOG',
    desc: 'Botão export na tabela',
  },
  {
    id: 'f3',
    title: 'Filtros avançados no painel',
    type: 'FEATURE',
    priority: 'HIGH',
    pts: 5,
    status: 'READY',
    desc: 'Filtrar por data, estado, nº pessoas',
  },
  {
    id: 'f4',
    title: 'Google OAuth',
    type: 'FEATURE',
    priority: 'HIGH',
    pts: 8,
    status: 'IN_PROGRESS',
    branch: 'feat/google-oauth',
    progress: 72,
    sprint: 3,
    agentId: 'a2',
    desc: 'Login com conta Google',
  },
  {
    id: 'f5',
    title: 'Email de confirmação automático',
    type: 'FEATURE',
    priority: 'HIGH',
    pts: 3,
    status: 'IN_PROGRESS',
    branch: 'feat/email-confirm',
    progress: 45,
    sprint: 3,
    agentId: 'a3',
    desc: 'Email após reserva confirmada',
  },
  {
    id: 'f6',
    title: 'Calendário de disponibilidade',
    type: 'FEATURE',
    priority: 'CRITICAL',
    pts: 8,
    status: 'IN_REVIEW',
    branch: 'feat/calendar',
    progress: 100,
    sprint: 3,
    agentId: 'a4',
    desc: 'Vista de calendário com slots',
  },
  {
    id: 'f7',
    title: 'Formulário mobile de reserva',
    type: 'FEATURE',
    priority: 'CRITICAL',
    pts: 5,
    status: 'IN_QA',
    branch: 'feat/booking-mobile',
    qa: 82,
    progress: 100,
    sprint: 3,
    agentId: 'a5',
    desc: 'Formulário responsivo para mobile',
    bugs: [
      { sev: 'HIGH', msg: 'Overflow em 375px no campo de data' },
      { sev: 'MEDIUM', msg: 'Botão sem loading state' },
    ],
  },
  {
    id: 'f8',
    title: 'Painel admin — lista de reservas',
    type: 'FEATURE',
    priority: 'HIGH',
    pts: 5,
    status: 'DONE',
    branch: 'feat/admin-panel',
    qa: 98,
    progress: 100,
    sprint: 3,
    mergedAt: 'Hoje, 09:12',
    desc: 'Tabela com todas as reservas',
  },
  {
    id: 'f9',
    title: 'Fix: modal de cancelamento',
    type: 'FIX',
    priority: 'HIGH',
    pts: 2,
    status: 'DONE',
    branch: 'fix/cancel-modal',
    qa: 100,
    progress: 100,
    sprint: 3,
    mergedAt: 'Ontem, 16:40',
    desc: 'Modal não fechava',
  },
];

// Pipeline Data
export const MOCK_PHASES: Phase[] = [
  {
    id: 'pm',
    label: 'PM Agent',
    short: 'PM',
    icon: '🧠',
    color: 'var(--accent)',
    colorRaw: '#7C6AFA',
    glowRaw: 'rgba(124,106,250,0.18)',
    status: 'done',
  },
  {
    id: 'arch',
    label: 'Arquitectura',
    short: 'ARCH',
    icon: '🏗️',
    color: 'var(--blue)',
    colorRaw: '#5BB8FF',
    glowRaw: 'rgba(91,184,255,0.15)',
    status: 'done',
  },
  {
    id: 'dev',
    label: 'Dev Team',
    short: 'DEV',
    icon: '⚡',
    color: 'var(--orange)',
    colorRaw: '#FB923C',
    glowRaw: 'rgba(251,146,60,0.15)',
    status: 'running',
    parallel: true,
  },
  {
    id: 'qa',
    label: 'QA & Testes',
    short: 'QA',
    icon: '🔍',
    color: 'var(--amber)',
    colorRaw: '#FFB547',
    glowRaw: 'rgba(255,181,71,0.15)',
    status: 'idle',
  },
  {
    id: 'fix',
    label: 'Bug Fix',
    short: 'FIX',
    icon: '🔄',
    color: 'var(--pink)',
    colorRaw: '#F472B6',
    glowRaw: 'rgba(244,114,182,0.15)',
    status: 'idle',
    isLoop: true,
  },
  {
    id: 'deploy',
    label: 'Deploy',
    short: '🚀',
    icon: '🚀',
    color: 'var(--green)',
    colorRaw: '#3DFFA0',
    glowRaw: 'rgba(61,255,160,0.15)',
    status: 'idle',
  },
];

export const MOCK_LOGS: string[] = [
  'Dev Team — 4 agentes paralelos',
  '[Frontend] Componentes React...',
  '[Backend] 11 endpoints REST criados',
  '[DB] Migrations Prisma geradas',
  '[Integration] ENV vars ✓',
  '2.847 linhas de código ✓',
];

// Team Data
export const MOCK_HUMANS: HumanMember[] = [
  {
    id: 'u1',
    name: 'DLoureiro',
    role: 'Product Owner',
    initials: 'DL',
    color: '#7C6AFA',
    online: true,
  },
  {
    id: 'u2',
    name: 'Ana Silva',
    role: 'Developer',
    initials: 'AS',
    color: '#5BB8FF',
    online: true,
  },
  {
    id: 'u3',
    name: 'Carlos M.',
    role: 'Stakeholder',
    initials: 'CM',
    color: '#3DFFA0',
    online: false,
  },
];

export const MOCK_AGENTS: AIAgent[] = [
  {
    id: 'a1',
    name: 'Scrum Master',
    model: 'Claude Sonnet',
    icon: '🧠',
    color: '#7C6AFA',
    active: true,
  },
  {
    id: 'a2',
    name: 'Frontend Dev',
    model: 'qwen2.5:14b',
    icon: '⚡',
    color: '#FB923C',
    active: true,
  },
  {
    id: 'a3',
    name: 'Backend Dev',
    model: 'qwen2.5:14b',
    icon: '⚙️',
    color: '#5BB8FF',
    active: false,
  },
  {
    id: 'a4',
    name: 'Architect',
    model: 'DeepSeek-R1',
    icon: '🏗️',
    color: '#FFB547',
    active: false,
  },
  {
    id: 'a5',
    name: 'QA Agent',
    model: 'Playwright',
    icon: '🔍',
    color: '#F472B6',
    active: false,
  },
];

export const MOCK_ACTIVITY: Activity[] = [
  {
    id: 1,
    time: '14:32',
    actor: 'QA Agent',
    ai: true,
    icon: '🔍',
    msg: 'f7 entrou em QA — 40 testes a correr',
    badge: 'badge-pink',
  },
  {
    id: 2,
    time: '14:28',
    actor: 'DLoureiro',
    ai: false,
    icon: '💬',
    msg: "Comentou em 'Calendário de disponibilidade'",
    badge: 'badge-purple',
  },
  {
    id: 3,
    time: '14:15',
    actor: 'Architect',
    ai: true,
    icon: '🏗️',
    msg: 'Code review aprovado — feat/calendar ✓',
    badge: 'badge-amber',
  },
  {
    id: 4,
    time: '13:50',
    actor: 'Frontend Dev',
    ai: true,
    icon: '⚡',
    msg: 'Commit: feat/google-oauth — 72% concluído',
    badge: 'badge-orange',
  },
  {
    id: 5,
    time: '09:12',
    actor: 'Sistema',
    ai: true,
    icon: '🚀',
    msg: 'feat/admin-panel → main. Deploy staging ✓',
    badge: 'badge-green',
  },
];

// PM Chat Questions
export const PM_QUESTIONS: Question[] = [
  {
    id: 'q1',
    text: 'Olá! Qual é a funcionalidade ou melhoria que queres adicionar?',
    type: 'open',
    ph: 'Descreve em linguagem natural...',
  },
  {
    id: 'q2',
    text: 'É algo novo ou uma melhoria do existente?',
    type: 'choice',
    opts: [
      'Nova funcionalidade',
      'Melhoria do existente',
      'Correcção de bug',
      'Mudança de design',
      'Optimização',
    ],
  },
  {
    id: 'q3',
    text: 'Qual é a urgência?',
    type: 'choice',
    opts: [
      '🚨 Crítico (produção)',
      '🔴 Alta (próximo sprint)',
      '🟡 Normal (backlog)',
      '🔵 Baixa',
    ],
  },
  {
    id: 'q4',
    text: 'Que parte do produto afecta?',
    type: 'choice',
    opts: [
      'Página específica',
      'Funcionalidade existente',
      'Toda a app',
      'Só o servidor',
      'Design global',
    ],
  },
  {
    id: 'q5',
    text: 'Como saberemos que está feito? Qual o resultado esperado?',
    type: 'open',
    ph: 'Ex: O utilizador consegue fazer login com Google...',
  },
];

// Projects for Dashboard
export const MOCK_PROJECTS = [
  {
    id: 'p1',
    name: 'Sistema de Reservas',
    sprint: 3,
    status: 'active' as const,
    team: 5,
    lastActivity: 'há 5 minutos',
  },
  {
    id: 'p2',
    name: 'E-commerce Platform',
    sprint: 1,
    status: 'active' as const,
    team: 3,
    lastActivity: 'há 2 horas',
  },
  {
    id: 'p3',
    name: 'Dashboard Analytics',
    sprint: null,
    status: 'completed' as const,
    team: 4,
    lastActivity: 'há 3 dias',
  },
];
